# Generated by Django 5.2.6 on 2025-09-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(help_text='Judul atau perihal surat', max_length=200)),
                ('nomor_surat', models.CharField(blank=True, help_text='Nomor resmi surat', max_length=100, null=True, unique=True)),
                ('tanggal_surat', models.DateField(help_text='Tanggal yang tertera pada surat')),
                ('pengirim', models.CharField(help_text='Asal atau pengirim surat', max_length=150)),
                ('penerima', models.CharField(help_text='Tujuan atau penerima surat', max_length=150)),
                ('file_pdf', models.FileField(help_text='File surat dalam format PDF', upload_to='media/')),
                ('tanggal_unggah', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Surat',
                'verbose_name_plural': 'Daftar Surat',
                'ordering': ['-tanggal_surat'],
            },
        ),
    ]
