# Generated by Django 5.2.6 on 2025-09-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudsurat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surat',
            name='kategori',
            field=models.CharField(blank=True, help_text='Kategori atau jenis surat', max_length=100, null=True),
        ),
    ]
