# Generated by Django 5.2.6 on 2025-09-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudsurat', '0002_surat_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriSurat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Nama kategori surat', max_length=100, unique=True)),
            ],
        ),
    ]
