# Generated by Django 4.2.24 on 2025-09-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudsurat', '0003_kategorisurat'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategorisurat',
            name='judul',
            field=models.CharField(blank=True, help_text='Judul atau perihal surat (opsional)', max_length=200, null=True),
        ),
    ]
