# Generated by Django 5.2.6 on 2025-09-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudsurat', '0004_kategorisurat_judul'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surat',
            options={'ordering': ['-tanggal_unggah'], 'verbose_name': 'Surat', 'verbose_name_plural': 'Daftar Surat'},
        ),
        migrations.RemoveField(
            model_name='surat',
            name='penerima',
        ),
        migrations.RemoveField(
            model_name='surat',
            name='pengirim',
        ),
        migrations.RemoveField(
            model_name='surat',
            name='tanggal_surat',
        ),
        migrations.AlterField(
            model_name='surat',
            name='kategori',
            field=models.CharField(default='Umum', help_text='Kategori atau jenis surat', max_length=100),
        ),
        migrations.AlterField(
            model_name='surat',
            name='nomor_surat',
            field=models.CharField(default='', help_text='Nomor resmi surat', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='tanggal_unggah',
            field=models.DateTimeField(auto_now_add=True, help_text='Waktu pengarsipan'),
        ),
    ]
