version: '3.8'

services:
  # Service untuk database PostgreSQL
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    ports:
      - "5432:5432"

  # Service untuk aplikasi Django
  web:
    build: .
    volumes:
      # Mount kode lokal ke container untuk live-reloading
      - .:/app
      - ./media:/app/media
    ports:
      - "8000:8000"
    # Membaca environment variables dari file .env
    env_file:
      - .env
    # Memastikan service 'db' berjalan sebelum 'web'
    depends_on:
      - db

# Volume untuk persistensi data database
volumes:
  postgres_data:

